### ISSUE TITLE
Some test on travis are failing

### ISSUE THREAD

**Issue by lslachciak** [Samsung/WATT#102]
34 passing (1s)
  2 failing
  1) test /routes/brackets.js GET /brackets should test /brackets:
      Uncaught AssertionError: expected 404 to equal 200
      + expected - actual
      -404
      +200
      
      at agent.get.end (test/bracketsTest.js:44:29)
      at Test.Request.callback (node_modules/superagent/lib/node/index.js:631:3)
      at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/index.js:795:18)
      at IncomingMessage.EventEmitter.emit (domain.js:441:20)
      at endReadableNT (_stream_readable.js:1125:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
  2) test /routes/brackets.js GET projectid normal should test get projectid:
      Uncaught AssertionError: expected 404 to equal 200
      + expected - actual
      -404
      +200
      
      at agent.get.end (test/bracketsTest.js:105:33)
      at Test.Request.callback (node_modules/superagent/lib/node/index.js:631:3)
      at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/index.js:795:18)
      at IncomingMessage.EventEmitter.emit (domain.js:441:20)
      at endReadableNT (_stream_readable.js:1125:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by lslachciak** [comment]
this is happening on travis only. 
npm test on local PC (ubuntu) is not producing such errors
