### ISSUE TITLE
./launch -d -n update fails

### ISSUE THREAD

**Issue by lslachciak** [Samsung/WATT#190]
Command executed on travis

`./launch -d -n update`

fails (also locally)

> 
> Download emsdk tool
> Traceback (most recent call last):
>   File "./launch", line 798, in <module>
>     returncode = main()
>   File "./launch", line 754, in main
>     emscripten_path = get_emscripten_path(args.emscripten_version, args.emscripten_path)
>   File "./launch", line 345, in get_emscripten_path
>     if not ensure_emsdk(emsdk_path):
>   File "./launch", line 315, in ensure_emsdk
>     tar = tarfile.open(dest_path)
>   File "/usr/lib/python2.7/tarfile.py", line 1678, in open
>     raise ReadError("file could not be opened successfully")
> tarfile.ReadError: file could not be opened successfully

**Comment by lslachciak** [comment]
note: if I bypass emscripten (-bpe), launch command succeeds:
`./launch -d -n update -bpe`
