### ISSUE TITLE
Build failed after #26

### ISSUE THREAD

**Issue by HunseopJeong** [Samsung/WATT#27]
Running "requirejs:.csslintrc" (requirejs) task
{ Error: Error: ERROR: module path does not exist: /Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/embedded-ext/.csslintrc/main.js for module named: main. Path is relative to: /Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server
    at /Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:28441:35

    at /Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:28326:19
    at /Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:3059:39
    at /Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:2999:25
    at Function.prim.nextTick (/Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:28077:9)
    at Object.errback (/Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:2998:26)
    at Object.callback (/Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:2984:23)
    at Object.then (/Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:3038:23)
    at build (/Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:28283:12)
    at runBuild (/Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:30291:17)
    at Object.execCb (/Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:1946:33)
    at Module.check (/Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:1133:51)
    at Module.enable (/Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:1426:22)
    at Module.init (/Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:1038:26)
    at /Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:1710:36
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

  originalError: 
   Error: ERROR: module path does not exist: /Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/embedded-ext/.csslintrc/main.js for module named: main. Path is relative to: /Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server
       at /Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:28441:35
       at Array.forEach (native)
       at /Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:28431:25
       at /Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:3041:37
       at /Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:2989:25
       at Function.prim.nextTick (/Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:28077:9)
       at Object.callback (/Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:2988:26)
       at Object.then (/Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:3038:23)
       at Object.start (/Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:3031:34)
       at Function.build._run (/Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:28343:23)
       at /Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:28282:26
       at /Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:3041:37
       at /Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:2989:25
       at Function.prim.nextTick (/Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:28077:9)
       at Object.callback (/Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:2988:26)
       at Object.then (/Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:3038:23)
       at Object.start (/Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:3031:34)
       at build (/Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:28259:23)
       at runBuild (/Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:30291:17)
       at Object.execCb (/Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:1946:33)
       at Module.check (/Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:1133:51)
       at Module.enable (/Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:1426:22)
       at Module.init (/Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:1038:26)
       at /Users/hunseopjeong/Source/opensource/WATT/libs/brackets-server/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:1710:36
       at _combinedTickCallback (internal/process/next_tick.js:67:7)
       at process._tickCallback (internal/process/next_tick.js:98:9)
    }
Fail to build. Please try rerun after fix build break.

**Comment by HunseopJeong** [comment]
I think we should remove the added csslintrc file and use same config in brackets-server.

**Comment by Kwanghyuk-Kim** [comment]
IMO, addEmbeddedExtesions() function in Gruntfile.js should check file param is directory or not because it will handle directory only.

**Comment by HunseopJeong** [comment]
That way is also good approach. Could you please fix it?

**Comment by Kwanghyuk-Kim** [comment]
Ok, I will. :)

**Comment by Kwanghyuk-Kim** [comment]
https://github.com/Samsung/WATT/pull/29 fixed this issue.
