### ISSUE TITLE
launch fails due to old setuptools version

### ISSUE THREAD

**Issue by andy-cho** [Samsung/WATT#74]
launch fails with below error,
```python
Traceback (most recent call last):
  File "./launch", line 623, in <module>
    returncode = main()
  File "./launch", line 571, in main
    ret, grunt_path = prepare_nodejs(args.npm)
  File "./launch", line 179, in prepare_nodejs
    if not ensure_nodejs():
  File "./launch", line 130, in ensure_nodejs
    ver = get_version(subprocess.check_output('node --version', shell=True))
  File "./launch", line 118, in get_version
    if (pkg_resources.parse_version(s).base_version):
AttributeError: 'tuple' object has no attribute 'base_version'
```
Since launch script works properly after upgrading setuptools via pip (e..g. pip install --upgrade setuptools), old version of parsing in setuptools are problematic.

Either
1. add checking routine for minimum version of setuptools (>= 8.0)
2. modify launch script to handle lower version of setuptools
```python
if hasattr(version, 'base_version'):
  ....
else:
  ....

**Comment by hs85jeong** [comment]
I fixed this issue with #76.
